function hyperthermia_treatment_gui()
    % إنشاء نافذة الواجهة الرئيسية
    fig = figure('Name', 'نظام محاكاة العلاج الحراري', ...
                'Position', [100, 100, 1000, 700], ...
                'NumberTitle', 'off', ...
                'Color', [0.95 0.95 0.98], ...
                'MenuBar', 'none', ...
                'ToolBar', 'none');

    % عنوان الواجهة مع تحسينات
    title_panel = uipanel(fig, 'Title', '', ...
                         'Position', [0.1 0.93 0.8 0.06], ...  % رفع العنوان لأعلى
                         'BackgroundColor', [0.4 0.6 0.8], ...
                         'BorderType', 'none');

    uicontrol(title_panel, 'Style', 'text', ...
              'String', 'نظام محاكاة العلاج الحراري للأورام', ...
              'Position', [10 5 980 40], ...
              'FontSize', 18, ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [1 1 1], ...
              'BackgroundColor', [0.4 0.6 0.8], ...
              'HorizontalAlignment', 'center');

    % لوحة التحكم بالمعطيات مع تحسينات التصميم
    panel = uipanel(fig, 'Title', 'معطيات النموذج', ...
                     'Position', [0.03, 0.45, 0.35, 0.45], ...  % رفع اللوحة لأعلى
                     'BackgroundColor', [0.92 0.94 0.96], ...
                     'ForegroundColor', [0.2 0.2 0.5], ...
                     'FontWeight', 'bold', ...
                     'FontSize', 12);

    % ألوان متناسقة للواجهة
    bg_color = [0.92 0.94 0.96];
    text_color = [0.2 0.2 0.5];
    edit_bg = [1 1 1];
    section_color = [0.85 0.9 0.95];

    % إحداثيات y الأولية للعناصر
    start_y = 350;
    delta_y = 30;

    % معلمات النسيج مع تحسينات
    uicontrol(panel, 'Style', 'text', ...
              'String', 'خصائص النسيج:', ...
              'Position', [10, start_y, 150, 25], ...
              'FontWeight', 'bold', ...
              'FontSize', 11, ...
              'BackgroundColor', section_color, ...
              'ForegroundColor', text_color, ...
              'HorizontalAlignment', 'left');

    % التوصيل الحراري
    uicontrol(panel, 'Style', 'text', ...
              'String', 'التوصيل الحراري (W/m°C):', ...
              'Position', [10, start_y-delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    k_edit = uicontrol(panel, 'Style', 'edit', ...
                       'String', '0.5', ...
                       'Position', [170, start_y-delta_y, 100, 25], ...
                       'FontSize', 10, ...
                       'BackgroundColor', edit_bg);

    % السعة الحرارية
    uicontrol(panel, 'Style', 'text', ...
              'String', 'السعة الحرارية (J/kg°C):', ...
              'Position', [10, start_y-2*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    cp_edit = uicontrol(panel, 'Style', 'edit', ...
                        'String', '3600', ...
                        'Position', [170, start_y-2*delta_y, 100, 25], ...
                        'FontSize', 10, ...
                        'BackgroundColor', edit_bg);

    % الكثافة
    uicontrol(panel, 'Style', 'text', ...
              'String', 'الكثافة (kg/m³):', ...
              'Position', [10, start_y-3*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    rho_edit = uicontrol(panel, 'Style', 'edit', ...
                         'String', '1050', ...
                         'Position', [170, start_y-3*delta_y, 100, 25], ...
                         'FontSize', 10, ...
                         'BackgroundColor', edit_bg);

    % معلمات الورم مع تحسينات
    uicontrol(panel, 'Style', 'text', ...
              'String', 'خصائص الورم:', ...
              'Position', [10, start_y-4*delta_y, 150, 25], ...
              'FontWeight', 'bold', ...
              'FontSize', 11, ...
              'BackgroundColor', section_color, ...
              'ForegroundColor', text_color, ...
              'HorizontalAlignment', 'left');

    % موقع الورم
    uicontrol(panel, 'Style', 'text', ...
              'String', 'موقع الورم (x,y) (cm):', ...
              'Position', [10, start_y-5*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    tumor_x_edit = uicontrol(panel, 'Style', 'edit', ...
                             'String', '5', ...
                             'Position', [170, start_y-5*delta_y, 70, 25], ...
                             'FontSize', 10, ...
                             'BackgroundColor', edit_bg);

    tumor_y_edit = uicontrol(panel, 'Style', 'edit', ...
                             'String', '5', ...
                             'Position', [250, start_y-5*delta_y, 70, 25], ...
                             'FontSize', 10, ...
                             'BackgroundColor', edit_bg);

    % نصف قطر الورم
    uicontrol(panel, 'Style', 'text', ...
              'String', 'نصف قطر الورم (cm):', ...
              'Position', [10, start_y-6*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    tumor_radius_edit = uicontrol(panel, 'Style', 'edit', ...
                                  'String', '2', ...
                                  'Position', [170, start_y-6*delta_y, 100, 25], ...
                                  'FontSize', 10, ...
                                  'BackgroundColor', edit_bg);

    % معلمات العلاج مع تحسينات
    uicontrol(panel, 'Style', 'text', ...
              'String', 'معلمات العلاج:', ...
              'Position', [10, start_y-7*delta_y, 150, 25], ...
              'FontWeight', 'bold', ...
              'FontSize', 11, ...
              'BackgroundColor', section_color, ...
              'ForegroundColor', text_color, ...
              'HorizontalAlignment', 'left');

    % قوة المصدر
    uicontrol(panel, 'Style', 'text', ...
              'String', 'قوة المصدر (W/m³):', ...
              'Position', [10, start_y-8*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    Q_edit = uicontrol(panel, 'Style', 'edit', ...
                       'String', '50000', ...
                       'Position', [170, start_y-8*delta_y, 100, 25], ...
                       'FontSize', 10, ...
                       'BackgroundColor', edit_bg);

    % زمن العلاج
    uicontrol(panel, 'Style', 'text', ...
              'String', 'زمن العلاج (دقيقة):', ...
              'Position', [10, start_y-9*delta_y, 150, 20], ...
              'FontSize', 10, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', bg_color, ...
              'ForegroundColor', text_color);

    treatment_time_edit = uicontrol(panel, 'Style', 'edit', ...
                                    'String', '30', ...
                                    'Position', [170, start_y-9*delta_y, 100, 25], ...
                                    'FontSize', 10, ...
                                    'BackgroundColor', edit_bg);

    % زر المحاكاة مع تحسينات
    simulate_btn = uicontrol(fig, 'Style', 'pushbutton', ...
                             'String', 'تشغيل المحاكاة', ...
                             'Position', [100, 40, 150, 40], ...  % رفع الزر لأعلى
                             'FontSize', 12, ...
                             'FontWeight', 'bold', ...
                             'ForegroundColor', [1 1 1], ...
                             'BackgroundColor', [0.2 0.6 0.3], ...
                             'Callback', @run_simulation);

 % محور للرسم مع تحسينات
    ax = axes('Parent', fig, 'Position', [0.4, 0.15, 0.55, 0.7], ...
              'FontName', 'Arial', ...  % يمكن تغييرها لخط يدعم العربية مثل 'Traditional Arabic'
              'Box', 'on', ...
              'XGrid', 'on', ...
              'YGrid', 'on');

    % تعيين إعدادات النص للغة العربية
    set(ax, 'DefaultTextFontName', 'Arial', ...  % أو أي خط آخر يدعم العربية
            'DefaultTextFontSize', 10, ...
            'DefaultTextFontWeight', 'normal', ...
            'DefaultTextInterpreter', 'none');  % تعطيل مفسر النص لتجنب مشاكل العرض

    title(ax, 'توزيع درجة الحرارة في النسيج', 'FontSize', 12, 'FontWeight', 'bold');
    xlabel(ax, 'المسافة الأفقية (cm)', 'FontSize', 10);
    ylabel(ax, 'المسافة العمودية (cm)', 'FontSize', 10);
    colormap(ax, 'jet');

    % دالة المحاكاة مع تصحيح الخطأ النهائي
    function run_simulation(~, ~)
        try
            % قراءة المعطيات من الواجهة
            k = str2double(get(k_edit, 'String'));
            cp = str2double(get(cp_edit, 'String'));
            rho = str2double(get(rho_edit, 'String'));
            tumor_x = str2double(get(tumor_x_edit, 'String'));
            tumor_y = str2double(get(tumor_y_edit, 'String'));
            tumor_radius = str2double(get(tumor_radius_edit, 'String'));
            Q = str2double(get(Q_edit, 'String'));
            treatment_time = str2double(get(treatment_time_edit, 'String')) * 60;

            % معلمات الشبكة
            Lx = 10; Ly = 10;
            Nx = 50; Ny = 50;
            dx = Lx/(Nx-1); dy = Ly/(Ny-1);

            % إنشاء meshgrid بشكل صحيح
            x_vec = linspace(0, Lx, Nx);
            y_vec = linspace(0, Ly, Ny);
            [X, Y] = meshgrid(x_vec, y_vec);

            % حساب قناع الورم
            tumor_mask = ((X-tumor_x).^2 + (Y-tumor_y).^2) <= tumor_radius^2;

            % معامل الانتشار الحراري
            alpha = k / (rho * cp);
            dt = 0.25 * min(dx^2, dy^2) / (2*alpha);

            % تهيئة درجة الحرارة
            T = ones(Ny, Nx) * 37; % درجة حرارة الجسم الطبيعية

            % حل معادلة الحرارة
            num_steps = round(treatment_time / dt);
            for n = 1:num_steps
                % حساب المشتقات الجزئية
                d2Tdy2 = (T(3:end,2:end-1) - 2*T(2:end-1,2:end-1) + T(1:end-2,2:end-1));
                d2Tdx2 = (T(2:end-1,3:end) - 2*T(2:end-1,2:end-1) + T(2:end-1,1:end-2));

                % تحديث درجة الحرارة
                T(2:end-1,2:end-1) = T(2:end-1,2:end-1) + alpha*dt*(d2Tdy2/dy^2 + d2Tdx2/dx^2);

                % إضافة تأثير المصدر الحراري
                T(tumor_mask) = T(tumor_mask) + dt * Q / (rho * cp);

                % شروط حدية
                T(1,:) = T(2,:);
                T(end,:) = T(end-1,:);
                T(:,1) = T(:,2);
                T(:,end) = T(:,end-1);
            end

            % عرض النتائج
            cla(ax);
            imagesc(ax, x_vec, y_vec, T);
            colorbar(ax);
            title(ax, sprintf('توزيع درجة الحرارة بعد %d دقيقة', treatment_time/60));
            hold(ax, 'on');

            % رسم حدود الورم بشكل صحيح
            contour_levels = [tumor_radius, tumor_radius]; % تحديد مستويات الكنتور
            contour(ax, X, Y, sqrt((X-tumor_x).^2 + (Y-tumor_y).^2), contour_levels, ...
                   'r', 'LineWidth', 1.5);

            hold(ax, 'off');

            % إظهار رسالة نجاح
            msgbox('تمت المحاكاة بنجاح!', 'نجاح', 'help');

        catch err
            errordlg(sprintf('حدث خطأ: %s', err.message), 'خطأ في المحاكاة');
        end
    end
end
